05-dom-document-loading: решение
js-tasks-ru/js-20200821-3_avdeev-denis pull request #5
Opened 2020-09-04 23:51 UTC by avdeevdenis

2020-09-04 23:58 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort "asc" correctly for "sortType" equal number
+ should sort "desc" correctly for "sortType" equal number
+ should have ability to be destroyed
- should sort "asc" correctly for "sortType" equal string
- should sort "desc" correctly for "sortType" equal string
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering
+ should have ability to be destroyed
```

2020-09-05 00:00 UTC, avdeevdenis commented on 05-dom-document-loading/2-sortable-table-v1/style.css
> +.sortable-table__cell_type_price::before {
знаю, что просите не менять системные файлы, но у меня диссонанс, в файле с примером `static.html` цены идут со значком валюты, в то же время в тесте проверяется текстовое содержимое без него 🤔 

<img src="https://i.ibb.co/grVKYNt/2020-09-05-02-53-36.png" width="600">

2020-09-05 00:09 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort "asc" correctly for "sortType" equal number
+ should sort "desc" correctly for "sortType" equal number
+ should have ability to be destroyed
- should sort "asc" correctly for "sortType" equal string
- should sort "desc" correctly for "sortType" equal string
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering
+ should have ability to be destroyed
```

2020-09-05 08:37 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- .travis.yml — изменен
- 05-dom-document-loading/2-sortable-table-v1/index.spec.js — изменен
```

2020-09-05 08:44 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- .travis.yml — изменен
- 05-dom-document-loading/2-sortable-table-v1/index.spec.js — изменен
```

2020-09-05 09:00 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- .travis.yml — изменен
- 05-dom-document-loading/2-sortable-table-v1/index.spec.js — изменен
```

2020-09-05 09:58 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort "asc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal string
+ should sort "asc" correctly for "sortType" equal number
+ should sort "desc" correctly for "sortType" equal number
+ should have ability to be destroyed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering
+ should have ability to be destroyed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-09-05 10:04 UTC, avdeevdenis commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        return new Intl.Collator(['ru', 'en'], { caseFirst: 'upper' }).compare(a, b);
Забавно, но если здесь использовать 
`a.localeCompare(b, 'default', { caseFirst: 'upper' });`, как изначально планировал, то [не проходят два теста](https://travis-ci.org/github/js-tasks-ru/js-20200821-3_avdeev-denis/builds/724418694) в pull-request'е:
- "should sort \"desc\" correctly for \"sortType\" equal string"
- "should sort \"asc\" correctly for \"sortType\" equal string"

Локально же проходят, версия `nvm, npm, node` совпадет с запускаемой средой. 

По `console.log` в `job log` я вижу массив `data`, отсортированным совсем не так, как ожидалось (по ссылке выше можно увидеть), не понимаю почему 🤔  @dosandk

2020-09-05 10:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-09-07 09:46 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +        if (NotificationMessage.isShowed) return;
логика должна быть следующая: Если на странице уже показан нотификейшен, следует его удалить и показать новый.
А судя по этому коду происходит следующее: если на странице уже есть нотификешен - новый не будет показан

Это нужно исправить

2020-09-07 09:47 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +        target?.append(this.element);
подумайте нужна ли вот такая проверка:
```
target?.
```
Возможно следует дать параметру `target` дефолтное значение?

2020-09-07 10:23 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    ACTIVE_SORT_FIELD = null; // ID поля, которое отсортировано в данный момент
Почему данные поля имеют значения `null`?
Какие типы данных Вы будете в них хранить?

Ну и еще

2020-09-07 10:25 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        if (!price) return '';
такие конструкции следует упрощать:
```
return price 
  ? `<div class="sortable-table__cell sortable-table__cell_type_price">${price}</div>`
  : '';
```

2020-09-07 10:25 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        if (!value) return '';
см. коммент выше

2020-09-07 10:26 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        if (this.matchesWithPrevious(field, order)) {
В чем задумка отдельного метода, если он просто делает проверку:

```
field === this.ACTIVE_SORT_FIELD && order === this.ACTIVE_SORT_ORDER
```

Почему бы это сразу не сделать на месте и не создавать лишний метод?

2020-09-07 10:52 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        return new Intl.Collator(['ru', 'en'], { caseFirst: 'upper' }).compare(a, b);
Это мог бы быть длинный ответ, но попробую упростить:

`a.localeCompare(b, 'default', { caseFirst: 'upper' });` - у данного вызова отсутствует локаль, параметр `default` - это просто заглушка, так как такой локали нет, с этой же целью можно было бы передать пустой массив.

Если локаль не задана, то используется локаль по умолчанию среды выполнения.
Подробнее можно почитать тут: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Intl#Locale_identification_and_negotiation

Теперь что касается Вашего решения - Вы сделали абсолютно верно передав локали ['ru', 'en']. 

Но вот вывод, что "но используя объект `Intl` - работает ожидаемо" сделали неверный, передайте те же локали в `localCompare` и все станет на свои места

2020-09-07 10:53 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        switch (order) {
В данном случае использование объекта более уместно:
```
const direction = {
  asc: 1,
  desc: -1
};
```

2020-09-07 10:54 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    saveActiveSortParams(field, order) {
этот метод является лишним, слишком сильно дробить код не следует

2020-09-07 10:56 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/style.css
> +.sortable-table__cell_type_price::before {
Этим можно пренебречь. Но я поправлю для будущих поколений

2020-09-07 10:58 UTC, dosandk requested changes
Вцелом хорошо, но NotificationMessage нужно поправить + другие мелкие замечания.

2020-09-07 13:23 UTC, avdeevdenis commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        return new Intl.Collator(['ru', 'en'], { caseFirst: 'upper' }).compare(a, b);
Понял, спасибо

2020-09-07 13:27 UTC, avdeevdenis commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        if (!price) return '';
@dosandk
как-по мне в том виде, что я написал - выглядит читабельнее, в остальном - кажется равнозначно. Если будет большая строка-шаблон, то значение `: ''` в самом конце визуально затеряется

2020-09-07 13:28 UTC, avdeevdenis commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        if (this.matchesWithPrevious(field, order)) {
У меня в голове живет сильный декомпозитор, который стремится все выносить)

2020-09-07 13:41 UTC, avdeevdenis commented on 05-dom-document-loading/1-notification/index.js
> +        target?.append(this.element);
`document.body`?
не знаю

2020-09-07 13:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-09-07 13:52 UTC, avdeevdenis commented
Поправил замечания
https://github.com/js-tasks-ru/js-20200821-3_avdeev-denis/pull/5/commits/05ff6ac551795d04b1e456cf362989ad3ffd69e0

2020-09-07 13:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-09-07 18:10 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +        target?.append(this.element);
если по умолчанию мы добавляем элемент в `document.body`, то данное значение мы можем использовать в качестве дефолтного значения:
```
showTimeouted(target = document.body) {
// ...
}
```

2020-09-07 18:12 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        if (!price) return '';
Для того чтобы значение не терялось операторы "?" и ":" пишут с новой строки

2020-09-07 18:12 UTC, dosandk approved these changes
good 👍

2020-09-07 18:13 UTC, merged